# This is a basic workflow to help you get started with Actions
name: cs260_workflow

on:
  # Triggers when something in the www path on the main branch of your repo changes
  push:
    branches: [ main ]
    paths: [ 'www/*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      # Use this marketplace step to copy files over SCP. 
      # This copies everything in the www dir of your repo to your /var/www/html directory        
      - name: Copy website files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: www
          remote: /var/www/html
          host: 137.184.80.39
          username: myannajm
          privateKey: ${{ secrets.KEY }}   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
